[phases.setup]
nixPkgs = ['nodejs_20', 'openssl']

[phases.install]
cmds = [
  'cd webapp',
  'npm ci --legacy-peer-deps',
  'npx prisma generate'
]

[phases.build]
cmds = [
  'cd webapp',
  'npm run build',
  'cp -r public .next/standalone/public',
  'cp -r .next/static .next/standalone/.next/static'
]

[start]
cmd = 'cd webapp/.next/standalone && node server.js'
